# Generated by Django 5.0.4 on 2024-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='stock',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(related_name='watchlists', to='stocks.stock'),
        ),
    ]
