# Generated by Django 5.0.4 on 2024-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.CharField(default=100, max_length=4),
            preserve_default=False,
        ),
    ]
